### ISSUE TITLE
Everquest 2 перевод возможен?

### ISSUE THREAD

**Issue by Gexon** [SnakeSel/PotBS_Russian#1]
Привет, я тут пытаюсь перевести игру Everquest 2.
Можно ли использовать твои файлы для игры Everquest 2?

**Comment by SnakeSel** [comment]
Привет. 
При условии, что игра использует такие же файлы перевода, все что можно взять, это конвертер из dat в dir, т.к. у другой игры будет свой перевод и сами файлы перевода не подойдут.

Еще могу поделиться небольшой утилитой для упрощения перевода: [https://ibb.co/c6JfLPT](url)

**Comment by Gexon** [comment]
Все понял, спасибо бро)
Утилита бы помогла, а то я уже собирался свое написать)

**Comment by SnakeSel** [comment]
[LangUI](https://drive.google.com/open?id=1rrAK8AGKeczk17jxqVbSKEyMg_jeW2EQ)

**Comment by Gexon** [comment]
спасибо, только эта прога просит библиотеки)
libcairo-gobject-2.dll
libgdk-3-0.dll
Скачал из интернета, но видимо версии не совпали и программа падает в обморок)

**Comment by Gexon** [comment]
Попробовал в ручную перевести текст.
Это работает!
Можно переводить, но не знаю насколько много, говорят квесты с сервера подгружаются.

**Comment by SnakeSel** [comment]
Перезалил версию для Windows. Не думал, что собирать GTK под винду так геморно

**Comment by Gexon** [comment]
Спасибо! Теперь работает)

**Comment by SnakeSel** [comment]
Удачи в переводе

**Comment by SnakeSel** [comment]
Перезалил программу.
Добавил перевод по шаблонам.

**Comment by SnakeSel** [comment]
[Перезалил программу](https://drive.google.com/open?id=1rrAK8AGKeczk17jxqVbSKEyMg_jeW2EQ). Добавил:
- отображение только не переведенных строк
- перевод через Google Translate
Можно прикрутить и Яндекс, но придется свой ключ API заводить

Если создавали файл шаблонов, то его необходимо переименовать в виде: tmpl_EN-RU
